export const NavbarList = [
  {
    navId: "nav1",
    navTitle: "terminology",
  },
  {
    navId: "nav2",
    navTitle: "basics1",
  },
];

export const QuestionList = {
  nav1: [
    {
      question: "What is CSS ?",
      cardId: "headingOne",
      collapseId: "collapseOne",
      collapseTarget: "#collapseOne",
      answers: [
        "CSS stands for Cascading Style Sheets with an emphasis placed on “Style” and the latest version is CSS 3.",
        "While Hypertext Markup Language (HTML) is used to structure a web document (defining things like headlines and paragraphs, and allowing you to embed images, video, and other media), Cascading Style Sheet language comes through and specifies your document’s style — page layouts, colors, and fonts (shoutout to font-family and font-style!) are all determined with CSS syntax, meaning that CSS is one important language for you to master in terms of styling your web pages! Think of HTML as the foundation (every house has one), and Cascading Style Sheets as the aesthetic choices (there’s a big difference between a Victorian mansion and a mid-century modern home).",
        "You need both to create a web page and JavaScript to make it interactive.",
        "CSS3 is the latest evolution of the Cascading Style Sheets language and aims at extending CSS2.1. It brings a lot of new features and additions, like rounded corners, shadows, gradients, transitions or animations, as well as new layouts like multi-columns, flexible box or grid layouts.",
      ],
    },
    {
      question: "How does CSS actually work ?",
      cardId: "headingTwo",
      collapseId: "collapseTwo",
      collapseTarget: "#collapseTwo",
      answers: [
        "When a browser displays a document, it must combine the document's content with its style information. It processes the document in a number of stages, which we've listed below. Bear in mind that this is a very simplified version of what happens when a browser loads a webpage, and that different browsers will handle the process in different ways. But this is roughly what happens.",
        "1. The browser loads the HTML (e.g. receives it from the network).",
        "2. It converts the HTML into a DOM (Document Object Model). The DOM represents the document in the computer's memory.",
        "3. The browser then fetches most of the resources that are linked to by the HTML document, such as embedded images, videos, and even linked CSS! JavaScript is handled a bit later on in the process, and we won't talk about it here to keep things simpler.",
        "4. The browser parses the fetched CSS, and sorts the different rules by their selector types into different 'buckets', e.g. element, class, ID, and so on. Based on the selectors it finds, it works out which rules should be applied to which nodes in the DOM, and attaches style to them as required (this intermediate step is called a render tree).",
        "5. The render tree is laid out in the structure it should appear in after the rules have been applied to it.",
        "6. The visual display of the page is shown on the screen (this stage is called painting).",
      ],
      answerImg:
        "https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works/rendering.svg",
      answerImgAlt: "how-does-css-work",
    },
    {
      question: "How to add CSS to HTML page ?",
      cardId: "headingThree",
      collapseId: "collapseThree",
      collapseTarget: "#collapseThree",
      answers: [
        "1. Inline CSS - <p style=”color:red; font-size: 20px;”>This is our first HTML code.</p>",
        "However, using inline styles is generally thought to be a bad idea. Because style rules are inserted directly into the HTML tag, the presentation of the document becomes intermingled with the content of the document, making the code difficult to maintain and defeating the purpose of CSS.",
        "2. Internal CSS - <head> <style > body {  background-color: grey;  }  h1 {  color: red;  margin-left: 75px;  }   </style>  </head>",
        "Internal CSS is one of the most popular CSS forms for updating, customizing, and modifying a single web pages unique styles. You can use the internal CSS by integrating the <style> element in the <head> section of a HTML web page. ",
        "3. External CSS - <link rel='stylesheet' href=mystyle.css>",
        "External CSS is one of the most often used CSS forms for updating, styling, and adjusting the different styles in a large number of HTML web pages at the same time. There are two ways to include an external style sheet in an HTML document. One method is to use the <link> tag in the HTML document head. Another option is to use a combination of external CSS functions and integrated CSS. ",
      ],
    },
    {
      question: "Styling React Using CSS",
      cardId: "headingFour",
      collapseId: "collapseFour",
      collapseTarget: "#collapseFour",
      answers: [
        "1. Inline Styling - h1 style={{color: 'red'}}>Hello Style!</h1>",
        "In JSX, JavaScript expressions are written inside curly braces, and since JavaScript objects also use curly braces, the styling in the example above is written inside two sets of curly braces {{}}.",
        "Since the inline CSS is written in a JavaScript object, properties with two names, like background-color, must be written with camel case syntax like backgroundColor.",
        "You can also create an object with styling information, and refer to it in the style attribute - <h1 style={mystyle}>Hello Style!</h1>",
        "2. CSS Stylesheet - import './App.css';",
        "You can write your CSS styling in a separate file, just save the file with the .css file extension, and import it in your application",
      ],
    },
    {
      question: "What is meant by Reset CSS ?",
      cardId: "headingFive",
      collapseId: "collapseFive",
      collapseTarget: "#collapseFive",
      answers: [
        "In the beginning, there was no standardisation on how styles worked, each browser implemented what it felt was right. One of the reasons you see so many questions about style errors in IE is because IE was the browser with the most dissimilarities from other browsers in terms of styling. Though IE has improved and so have other browsers they still apply their own borders, padding and margins, zoom, fonts to elements to give their own unique feel to pages. One example is, chrome gives its own yellow borders to text boxes. The 'reset' actually 'resets' all these styles to zero/none, so that you don't see any styles you haven't applied to your page.",
        "If these styles are not reset, you will see unwanted styles/effects and things breaking. Its generally recommended to reset the browser's styles.",
      ],
    },
    {
      question: "What is SASS?",
      cardId: "headingSix",
      collapseId: "collapseSix",
      collapseTarget: "#collapseSix",
      answers: [
        "SASS (Syntactically Awesome Stylesheets) is a CSS preprocessor that extends CSS with features like variables, nested rules, mixins, and functions, allowing for more efficient and maintainable stylesheets. It compiles into regular CSS, providing enhanced functionality and organization for complex projects.",
        "Features of SASS",
        "1. Variables: Store values like colors, fonts, or any CSS value, making styles reusable.",
        "2. Nesting: Nest CSS selectors in a way that follows the same visual hierarchy as your HTML.",
        "3. Partials: Use @import to include external Sass files, keeping styles modular and organized.",
        "4. Mixins: Define reusable chunks of code, allowing you to avoid repetitive styles.",
        "5. Inheritance: Use @extend to share a set of CSS properties from one selector to another, simplifying the style management.",
      ],
    },
    {
      question: "What is SCSS?",
      cardId: "headingSeven",
      collapseId: "collapseSeven",
      collapseTarget: "#collapseSeven",
      answers: [
        "SCSS (Sassy CSS) is a syntax of SASS, offering a more CSS-like syntax. It includes features like variables, nesting, mixins, and inheritance while maintaining full compatibility with standard CSS. SCSS files use the .scss extension and enhance CSS with advanced functionalities for easier and more maintainable styling.",
        "Features of SCSS",
        "1. Variables: Store reusable values like colors and fonts for consistent styling.",
        "2. Nesting: Nest CSS selectors in a hierarchical manner for better readability.",
        "3. Mixins: Create reusable chunks of styles, avoiding repetitive code.",
        "4. Inheritance: Use @extend to share styles between selectors, simplifying the codebase.",
        "5. Partials and Importing: Modularize CSS using @import, keeping styles organized and maintainable.",
      ],
    },
    {
      question: "Which type of CSS holds the highest priority?",
      cardId: "headingEight",
      collapseId: "collapseEight",
      collapseTarget: "#collapseEight",
      answers: [
        "1. As Inline has the highest priority, any styles that are defined in the internal and external style sheets are overridden by Inline styles.",
        "2. Internal or Embedded stands second in the priority list and overrides the styles in the external style sheet.",
        "3. External style sheets have the least priority. If there are no styles defined either in the inline or internal style sheet then external style sheet rules are applied for the HTML tags.",
      ],
    },
    {
      question: "Adaptive design and Responsive design ?",
      cardId: "headingNine",
      collapseId: "collapseNine",
      collapseTarget: "#collapseNine",
      answers: [
        "1. Adaptive Design:",
        "Main focus is to develop a website in multiple fixed layout sizes.",
        "Offers good control over the design to develop variation in screens.",
        "It is very time-consuming and takes a lot of effort to build the best possible adaptive design as examining it will need to go for many options with respect to the realities of the end user.",
        "There are six standard screen sizes for the appropriate layouts; they are 320px, 480px, 760px, 960px, 1200px, 1600px to design.",
        "2. Responsive Design",
        "Main focus is to show content with respect to browser space.",
        "Offers less control over the design.",
        "It takes less time to build the design and there is no screen size issue irrespective of content.",
        "It uses CSS media queries to design the screen layouts with respect to specific devices and property changes in the screen.",
      ],
    },
    {
      question: "Best CSS Frameworks ?",
      cardId: "headingTen",
      collapseId: "collapseTen",
      collapseTarget: "#collapseTen",
      answers: [
        "Bootstrap",
        "Foundation",
        "Bulma",
        "UIKit",
        "Semantic UI",
        "Materialize",
        "Pure",
        "Tailwind CSS",
      ],
    },
    // {
    //   question: "Cascading aspect in CSS",
    //   cardId: "headingFive",
    //   collapseId: "collapseFive",
    //   collapseTarget: "#collapseFive",
    //   answers: [
    //     "The cascading aspect of CSS plays a crucial role in determining how styles are applied to elements within a webpage. By following a hierarchical order, CSS allows more specific rules to override general ones. Styles cascade from parent to child elements, including rules from external stylesheets, embedded styles, and inline styles for the final appearance of webpage elements.",
    //     "Cascading refers to the process by which styles are applied to HTML elements. It involves a set of rules that dictate how conflicting styles are resolved.",
    //     "1. Hierarchy of Styles: Styles cascade from parent elements to child elements. External stylesheets, embedded styles, and inline styles all contribute to the final appearance of elements. When multiple conflicting styles exist, the one with higher specificity takes precedence.",
    //     "2. Specificity Explained: Specificity determines which style rule applies when there are conflicting selectors.Specificity is calculated based on the combination of selectors used.Inline styles have the highest specificity, followed by IDs, classes, and element selectors.",
    //   ],
    // },
  ],
  nav2: [],
  nav3: [],
};
